/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 17:24:14 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      option0.setArgs((-2484));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-2484), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      assertEquals((-1), option0.getArgs());
      
      option0.setArgs(0);
      boolean boolean0 = option0.acceptsArg();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("8");
      Option.Builder option_Builder1 = option_Builder0.required(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.isValuesEmpty();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue("");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.required();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isRequired();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      option0.setOptionalArg(true);
      boolean boolean0 = option0.hasOptionalArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.processValue("LnqZ");
      option0.getValuesList();
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.setValueSeparator('5');
      char char0 = option0.getValueSeparator();
      assertEquals('5', char0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      option0.setValueSeparator('w');
      char char0 = option0.getValueSeparator();
      assertEquals('w', char0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String string0 = option0.getValue((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue("");
      String string0 = option0.getValue("Deprecated");
      assertFalse(option0.hasValueSeparator());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue("");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.since("~fO");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      String string0 = option0.getOpt();
      assertEquals("8", string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      String string0 = option0.getLongOpt();
      assertEquals("LnqZ", string0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      String string0 = option0.getLongOpt();
      assertEquals("", string0);
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setLongOpt("");
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      option_Builder0.desc("");
      Option option0 = option_Builder0.get();
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder2 = option_Builder1.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder2.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      int int0 = option0.getArgs();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", false, (String) null);
      option0.setArgName("Te(S)O~W9Hns");
      option0.getArgName();
      assertEquals("", option0.getLongOpt());
      assertTrue(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgName("");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option option0 = new Option((String) null, true, "wm/cjyNxQZ@3gnp%u");
      option0.acceptsArg();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      option0.processValue("");
      boolean boolean0 = option0.acceptsArg();
      assertEquals("", option0.getLongOpt());
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, false, "=  ");
      // Undeclared exception!
      try { 
        option0.setType((Object) "=  ");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("VnK+KtzYTNO=v+IE5Q");
      Option option0 = option_Builder1.get();
      option0.setArgs((-1891));
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.processValue("LnqZ");
      try { 
        option0.getValue((-2));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option((String) null, true, "");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("<f:B");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '<'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("ds{H", true, "^=UH9tFhy");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'ds{H' contains an illegal character : '{'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("08z2zPWj<p", " [ARG]", true, " [ARG]");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option '08z2zPWj<p' contains an illegal character : '<'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("\"", "\"");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '\"'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      boolean boolean0 = option0.isDeprecated();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isDeprecated();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.valueSeparator('$');
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('$', option0.getValueSeparator());
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      assertFalse(option0.hasArg());
      
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgs(2725);
      boolean boolean0 = option0.hasArgs();
      assertEquals(2725, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.hasArgs();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgs(2725);
      option0.hasArg();
      assertEquals(2725, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      assertFalse(option0.hasArgs());
      
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option((String) null, true, "");
      option0.getValue();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", false, (String) null);
      boolean boolean0 = option0.hasArg();
      assertTrue(option0.hasLongOpt());
      assertEquals("", option0.getLongOpt());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      option0.getValueSeparator();
      assertEquals("", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option("LnqZ", "", true, "");
      option0.hasOptionalArg();
      assertEquals("", option0.getLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Class<Integer> class0 = Integer.class;
      option0.setType(class0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      String string0 = option0.toString();
      assertEquals("[ Option LnqZ LnqZ [ARG] :: LnqZ :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("4Y");
      Option.Builder option_Builder2 = option_Builder1.deprecated();
      Option option0 = option_Builder2.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option '4Y': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder1.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder1.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'null''K}YyV|;b?4U06_}': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.setOptionalArg(true);
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasOptionalArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasLongOpt();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      boolean boolean0 = option0.hasLongOpt();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option option0 = option_Builder1.get();
      String string0 = option0.toString();
      assertEquals("[ Option null K}YyV|;b?4U06_}[ARG...] :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option option0 = new Option("XqADn", (String) null);
      option0.setArgs(229);
      option0.toString();
      assertEquals(229, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option((String) null, "}");
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.argName("~fO");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      String[] stringArray0 = option0.getValues();
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      option0.processValue("8");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option option0 = new Option("XqADn", (String) null);
      option0.setArgs(229);
      option0.processValue("XqADn");
      option0.getValue("Optio/tn '");
      assertEquals(229, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      String string0 = option0.getValue(45);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      option0.processValue("8");
      try { 
        option0.getValue(201);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 201, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      String string0 = option0.getValue("8");
      assertEquals("8", string0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      assertEquals(1, option0.getArgs());
      
      option0.processValue("LnqZ");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.getKey();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option option0 = new Option("XqADn", (String) null);
      Option option1 = new Option((String) null, false, "[ Option XqADn[ARG...] :: null :: class java.lang.String ]");
      boolean boolean0 = option0.equals(option1);
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
      assertFalse(option1.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option option0 = new Option((String) null, "");
      Option option1 = (Option)option0.clone();
      assertFalse(option1.hasLongOpt());
      
      option1.setLongOpt("2<^2_GsQsHpS/#");
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Option option1 = (Option)option0.clone();
      boolean boolean0 = option0.equals(option1);
      assertTrue(boolean0);
      assertNotSame(option1, option0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.equals(option0);
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      Object object0 = new Object();
      boolean boolean0 = option0.equals(object0);
      assertTrue(option0.hasArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.hasArg();
      Option option0 = option_Builder0.get();
      option0.processValue("");
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.hasArg();
      Option option0 = option_Builder0.get();
      option0.processValue("");
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      assertEquals((-1), option0.getArgs());
      
      option0.setArgs((-2));
      option0.processValue("~uN2eu'Pumzuf/");
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      Option.Builder option_Builder2 = option_Builder0.optionalArg(true);
      assertSame(option_Builder2, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.getType();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      // Undeclared exception!
      try { 
        option0.addValue("");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option option0 = new Option((String) null, "org.apache.commons.cli.OptionValidator", true, (String) null);
      option0.hashCode();
      assertTrue(option0.hasArg());
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      option0.isRequired();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option((String) null, "}");
      String string0 = option0.getDescription();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option("LnqZ", "LnqZ", true, "LnqZ");
      option0.clearValues();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setDescription("~uN2eu'Pumzuf/");
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      int int0 = option0.getId();
      assertEquals(75, int0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option option0 = new Option((String) null, "}");
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertEquals((-1), option0.getArgs());
      assertNotNull(converter1);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder0.get();
      assertFalse(option0.hasArg());
      
      option0.setArgs((-2));
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option("8", "8", true, "8");
      option0.setRequired(false);
      assertFalse(option0.isRequired());
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Class<String> class0 = String.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArgs();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs((-1));
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      option_Builder0.hasArg();
      option_Builder0.valueSeparator('$');
      Option option0 = option_Builder0.get();
      assertTrue(option0.hasArg());
      
      option0.processValue("");
      assertTrue(option0.hasValueSeparator());
      assertEquals('$', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder1.longOpt("K}YyV|;b?4U06_}");
      Option option0 = option_Builder1.get();
      String string0 = option0.toString();
      assertEquals((-1), option0.getArgs());
      assertEquals("[ Option null K}YyV|;b?4U06_} Deprecated :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.converter(converter0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("7W");
      Option option0 = option_Builder0.get();
      option0.getValuesList();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      assertSame(option_Builder0, option_Builder1);
  }
}
